-   id: go-fmt
    name: 'go fmt'
    entry: go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `gofmt`, requires golang"
-   id: golangci-lint
    name: 'golangci-lint'
    entry: golangci-lint.sh
    types: [go]
    language: 'script'
    pass_filenames: false
    description: "Runs `golangci-lint`, requires https://github.com/golangci/golangci-lint"
-   id: go-unit-tests
    name: 'go-unit-tests.sh'
    entry: go-unit-tests.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go test`"

