-   id: go-fmt
    name: 'go fmt'
    entry: go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `gofmt`, requires golang"
# ==============================================================================
# golangci-lint-mod
#   * Folder-Based
#   * Recursive
#   * Targets first parent folder with a go.mod file
#   * Executes if any .go files modified
#   * Executes if go.mod modified
# ==============================================================================
-   id: golangci-lint-mod
    name: 'golangci-lint-mod'
    entry: golangci-lint.sh
    files: '(\.go$)|(\bgo\.mod$)'
    exclude: '(^|/)vendor/'
    language: 'script'
    description: "Run 'cd $(mod_root $FILE); golangci-lint run [$ARGS] ./...' for each staged .go file"
    pass_filenames: true
    require_serial: true
# ==============================================================================
# go-test-repo-mod
#   * Repo-Based
#   * Recursive
#   * Targets ALL folders with a go.mod file
#   * Executes if any .go files modified
#   * Executes if go.mod modified
# ==============================================================================
-   id: go-test-repo-mod
    name: 'go-test-repo-mod'
    entry: go-test-repo-mod.sh
    files: '(\.go$)|(\bgo\.mod$)'
    exclude: '(^|/)vendor/'
    language: 'script'
    description: "Run 'cd $(mod_root); go test [$ARGS] ./...' for each module in the repo"
    pass_filenames: false

