-   id: go-fmt
    name: 'go fmt'
    entry: go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `gofmt`, requires golang"
-   id: golangci-lint
    name: 'golangci-lint'
    entry: golangci-lint.sh
    types: [go]
    language: 'script'
    pass_filenames: false
    description: "Runs `golangci-lint`, requires https://github.com/golangci/golangci-lint"

# ==============================================================================
# go-test-repo-mod
#   * Repo-Based
#   * Recursive
#   * Targets ALL folders with a go.mod file
#   * Executes if any .go files modified
#   * Executes if go.mod modified
# ==============================================================================
-   id: go-unit-tests
    name: 'go-test-repo-mod'
    entry: go-unit-tests.sh
    files: '(\.go$)|(\bgo\.mod$)'
    exclude: '(^|/)vendor/'
    language: 'script'
    description: "Run 'cd $(mod_root); go test [$ARGS] ./...' for each module in the repo"
    pass_filenames: false

